### ISSUE TITLE
unable to remap ports

### ISSUE THREAD

**Issue by ogg1e** [thost96/docker-omada#13]
Is there a way to access the http ui from the host machine?

If you remap the ports (1043:8043), and try to connect (localhost:1043) you will get redirected to https://localhost:8043/login.
If you add network_mode:host, you then get Port 8088 is already in use. Release the port and try again.

**Comment by thost96** [comment]
Hi @ogg1e,

sorry for the massive delay. I added the env options HTTPPORT and HTTPSPORT to the latest images. With these you can set a custom port for both interfaces at container creation. This also works on network mode host. If you don't run on host network, you need to publish the exact custom port inside and outside the container (e.g. --port 8000:8000 if --env HTTPPORT=8000 was set), as normal mapping won't work by design of the tp-link software itself. 

Hope this solves your problem.

**Comment by thost96** [comment]
Closing this as issue is fixed and no response
